### ISSUE TITLE
Use LDAP for directory module

### ISSUE THREAD

**Issue by tomshen** [ScottyLabs/cmupy#3]

**Comment by tomshen** [comment]
Actually, instead of using LDAP directly, this library should just use https://apis.scottylabs.org/documentation/directory.

**Comment by RONNCC** [comment]
note cmu's ldap has a ton of restrictions e.g. you can only get resuts if your query has a limit of like 5 people or so  :( maybe ref in docs?

**Comment by RONNCC** [comment]
i believe that is because it's anon ldap  - but i'm not sure...also there are multiple ldap's around campus like CS's

**Comment by tomshen** [comment]
This should still use the ScottyLabs API. If we want to move away from LDAP, that's where it should happen.

**Comment by RONNCC** [comment]
Makes sense :) - any chance of us getting access privileges for more core directories things that CMU has?

**Comment by jez** [comment]
Right now we're in the process of finalizing our existing APIs so that we
can put them in a maintainable state. There are no plans to pursue
developing more APIs. If this is something you're interested in taking the
lead on, you should show up to a meeting so we can point you in the right
directions. You can find our meeting times on our website.
